# Generated by Django 5.2.15 on 2026-06-05 21:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('github_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_repository_id', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512)),
                ('owner_login', models.CharField(max_length=255)),
                ('private', models.BooleanField(default=True)),
                ('default_branch', models.CharField(blank=True, max_length=255)),
                ('html_url', models.URLField(blank=True)),
                ('selected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unselected_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('github_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_repositories', to='github_app.githubinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_repositories', to='accounts.customerorganization')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['owner_login', 'name'], name='repositorie_owner_l_a5d21e_idx'), models.Index(fields=['unselected_at', 'deleted_at'], name='repositorie_unselec_b9fcaf_idx')],
            },
        ),
    ]
