import { Activity, Gauge, GitPullRequest, ShieldCheck } from "lucide-react"

import type { FirstReportViewModel } from "../first-report-view-model"
import { StatCard } from "../components/report-primitives"

type SummaryMetricsProps = {
  constitution: FirstReportViewModel["constitution"]
  entropy: FirstReportViewModel["entropy"]
  prPlanCount: number
  session: FirstReportViewModel["session"]
}

export function SummaryMetrics({
  constitution,
  entropy,
  prPlanCount,
  session,
}: SummaryMetricsProps) {
  const selectedOpportunityLabel =
    session.selectedCount === 1
      ? "1 opportunity selected"
      : `${session.selectedCount} opportunities selected`

  return (
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <StatCard
        icon={Gauge}
        label="Repository Entropy Score"
        value={entropy.overall}
        detail={`${entropy.classification}; forecast ${entropy.forecast.predictedOverall} over ${entropy.forecast.horizonDays} days.`}
      />
      <StatCard
        icon={ShieldCheck}
        label="Constitution Coverage"
        value={constitution.completeness}
        detail={`${constitution.openQuestionCount} open constitution questions.`}
      />
      <StatCard
        icon={Activity}
        label="Session Status"
        value={session.status}
        detail={`${session.duration}; ${selectedOpportunityLabel}.`}
      />
      <StatCard
        icon={GitPullRequest}
        label="Focused PR Plans"
        value={prPlanCount}
        detail={`${prPlanCount} generated by the latest session.`}
      />
    </section>
  )
}
