# Generated by Django 5.2.15 on 2026-06-06 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('github_app', '0002_githubinstallation_html_url'),
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('github_installation_synced', 'GitHub installation synced'), ('managed_repository_selected', 'Managed repository selected'), ('managed_repository_unselected', 'Managed repository unselected')], max_length=64)),
                ('source', models.CharField(default='github_app_oauth_callback', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('github_installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='github_app.githubinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='accounts.customerorganization')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='repositories.managedrepository')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='common_audi_event_t_37c069_idx'), models.Index(fields=['organization', 'created_at'], name='common_audi_organiz_fc2b9d_idx'), models.Index(fields=['repository', 'created_at'], name='common_audi_reposit_708224_idx')],
            },
        ),
    ]
