# Generated by Django 5.2.15 on 2026-06-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('github_installation_synced', 'GitHub installation synced'), ('managed_repository_selected', 'Managed repository selected'), ('managed_repository_unselected', 'Managed repository unselected'), ('maintenance_pr_created', 'Maintenance PR created'), ('maintenance_pr_creation_failed', 'Maintenance PR creation failed')], max_length=64),
        ),
    ]
