# Generated by Django 5.2.15 on 2026-06-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('github_installation_synced', 'GitHub installation synced'), ('managed_repository_selected', 'Managed repository selected'), ('managed_repository_unselected', 'Managed repository unselected'), ('maintenance_pr_created', 'Maintenance PR created'), ('maintenance_pr_creation_failed', 'Maintenance PR creation failed'), ('maintenance_pr_outcome_recorded', 'Maintenance PR outcome recorded'), ('gardener_profile_updated', 'Gardener profile updated'), ('analysis_stored', 'Repository analysis stored'), ('session_trigger_enqueued', 'Session trigger enqueued'), ('session_trigger_failed', 'Session trigger failed')], max_length=64),
        ),
    ]
