# Generated by Django 5.2.15 on 2026-06-06 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryCommitTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commits_since_session', models.PositiveIntegerField(default=0)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commit_tracker', to='repositories.managedrepository')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
