# Generated by Django 5.2.15 on 2026-06-06 21:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('repositories', '0001_initial'),
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryAutomationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autonomy_mode', models.CharField(choices=[('conservative', 'Conservative'), ('assisted', 'Assisted'), ('autonomous', 'Autonomous')], default='autonomous', max_length=32)),
                ('manual_trigger_enabled', models.BooleanField(default=True)),
                ('scheduled_trigger_enabled', models.BooleanField(default=True)),
                ('commit_trigger_enabled', models.BooleanField(default=True)),
                ('risky_module_trigger_enabled', models.BooleanField(default=True)),
                ('pr_opened_trigger_enabled', models.BooleanField(default=True)),
                ('ci_failure_trigger_enabled', models.BooleanField(default=True)),
                ('commit_threshold', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_automation_policies', to='accounts.customerorganization')),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation_policy', to='repositories.managedrepository')),
            ],
            options={
                'ordering': ['repository__full_name'],
                'indexes': [models.Index(fields=['organization', 'autonomy_mode'], name='triggers_re_organiz_d8221f_idx')],
            },
        ),
    ]
