# Generated by Django 5.2.15 on 2026-06-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0002_repositoryautomationpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryautomationpolicy',
            name='autonomy_mode',
            field=models.CharField(choices=[('conservative', 'Conservative'), ('assisted', 'Assisted'), ('autonomous', 'Autonomous')], default='conservative', max_length=32),
        ),
        migrations.AlterField(
            model_name='repositoryautomationpolicy',
            name='ci_failure_trigger_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repositoryautomationpolicy',
            name='commit_trigger_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repositoryautomationpolicy',
            name='pr_opened_trigger_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repositoryautomationpolicy',
            name='risky_module_trigger_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repositoryautomationpolicy',
            name='scheduled_trigger_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
