# Generated by Django 5.2.15 on 2026-06-06 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_pr_size', models.CharField(default='small', max_length=32)),
                ('accepted_categories', models.JSONField(blank=True, default=list)),
                ('rejected_categories', models.JSONField(blank=True, default=list)),
                ('reverted_categories', models.JSONField(blank=True, default=list)),
                ('learned_protected_patterns', models.JSONField(blank=True, default=list)),
                ('review_preferences', models.JSONField(blank=True, default=list)),
                ('updated_from_pr_outcomes', models.JSONField(blank=True, default=list)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gardener_profile', to='repositories.managedrepository')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
