# Generated by Django 5.2.15 on 2026-06-07 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_repositoryanalysis_baseline_promoted_at_and_more'),
        ('gardener_sessions', '0002_gardeningsession_result'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardeningsession',
            name='baseline_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_gardening_sessions', to='analysis.repositoryanalysis'),
        ),
        migrations.AddField(
            model_name='gardeningsession',
            name='current_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_gardening_sessions', to='analysis.repositoryanalysis'),
        ),
        migrations.AddField(
            model_name='gardeningsession',
            name='drift_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gardeningsession',
            name='post_pr_refresh_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_pr_refresh_gardening_sessions', to='analysis.repositoryanalysis'),
        ),
        migrations.AddIndex(
            model_name='gardeningsession',
            index=models.Index(fields=['repository', 'current_analysis'], name='gardener_se_reposit_5edaf9_idx'),
        ),
    ]
