# Generated by Django 5.2.15 on 2026-06-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardener_sessions", "0003_gardeningsession_baseline_analysis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gardeningsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                default="queued",
                max_length=32,
            ),
        ),
    ]
