# Generated by Codex on 2026-06-06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenancePRPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gardening_session_id", models.CharField(db_index=True, max_length=255)),
                ("branch_name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("risk_tier", models.CharField(db_index=True, max_length=64)),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                ("changed_paths", models.JSONField(blank=True, default=list)),
                ("pr_body_sections", models.JSONField(blank=True, default=dict)),
                ("required_checks", models.JSONField(blank=True, default=list)),
                ("blocked", models.BooleanField(db_index=True, default=False)),
                ("block_reason", models.TextField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_pr_plans",
                        to="repositories.managedrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["repository", "gardening_session_id"],
                        name="maintenance_reposit_3a60f6_idx",
                    ),
                    models.Index(
                        fields=["repository", "blocked"],
                        name="maintenance_reposit_6996f4_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("repository", "gardening_session_id", "branch_name"),
                        name="unique_pr_plan_branch_per_repo_session",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MaintenancePRPlanOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gardening_session_id", models.CharField(db_index=True, max_length=255)),
                ("maintenance_opportunity_id", models.CharField(max_length=255)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_links",
                        to="maintenance_prs.maintenanceprplan",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_pr_plan_opportunities",
                        to="repositories.managedrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["repository", "gardening_session_id"],
                        name="maintenance_reposit_7706d8_idx",
                    ),
                    models.Index(
                        fields=["maintenance_opportunity_id"],
                        name="maintenance_mainten_f29025_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "maintenance_opportunity_id"),
                        name="unique_opportunity_per_pr_plan",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "repository",
                            "gardening_session_id",
                            "maintenance_opportunity_id",
                        ),
                        name="unique_pr_plan_opportunity_per_repo_session",
                    )
                ],
            },
        ),
    ]
