# Generated by Django 5.2.15 on 2026-06-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_prs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceprplan',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='maintenanceprplan',
            name='created_branch_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maintenanceprplan',
            name='created_pr_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceprplan',
            name='created_pr_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenanceprplan',
            name='execution_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenanceprplan',
            name='execution_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
    ]
