# Generated by Codex on 2026-06-06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_prs", "0002_maintenanceprplan_approval_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceprplan",
            name="confidence_threshold",
            field=models.FloatField(
                default=0.9,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
