# Generated by Django 5.2.15 on 2026-06-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_prs', '0003_maintenanceprplan_confidence_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceprplan',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
