# Generated by Django 5.2.15 on 2026-06-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_prs', '0004_maintenanceprplan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceprplan',
            name='merge_commit_sha',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
