# Generated by Django 5.2.15 on 2026-06-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_prs', '0005_maintenanceprplan_merge_commit_sha'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceprplan',
            name='outcome_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maintenanceprplan',
            name='terminal_outcome',
            field=models.CharField(blank=True, choices=[('merged', 'Merged'), ('closed', 'Closed'), ('reverted', 'Reverted')], db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='maintenanceprplan',
            name='terminal_outcome_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
