# Generated by Django 5.2.15 on 2026-06-06 18:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('analysis', '0001_initial'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryComplexity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('complete', 'Complete')], default='pending', max_length=16)),
                ('loc', models.PositiveIntegerField(blank=True, null=True)),
                ('module_count', models.PositiveIntegerField(blank=True, null=True)),
                ('contributor_count', models.PositiveIntegerField(blank=True, null=True)),
                ('loc_score', models.FloatField(default=0.0)),
                ('module_score', models.FloatField(default=0.0)),
                ('contributor_score', models.FloatField(default=0.0)),
                ('weighted_score', models.FloatField(default=0.0)),
                ('multiplier', models.FloatField(default=1.0)),
                ('missing_inputs', models.JSONField(blank=True, default=list)),
                ('calculation_version', models.CharField(default='complexity.v1.equal_thirds', max_length=64)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_complexities', to='accounts.customerorganization')),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complexity', to='repositories.managedrepository')),
                ('source_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complexity_calculations', to='analysis.repositoryanalysis')),
            ],
            options={
                'ordering': ['repository__full_name'],
                'indexes': [models.Index(fields=['organization', 'input_status'], name='billing_rep_organiz_e238da_idx'), models.Index(fields=['calculated_at'], name='billing_rep_calcula_8380bc_idx')],
            },
        ),
    ]
