# Generated by Django 5.2.15 on 2026-06-06 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_code', models.CharField(default='managed_repository_base', max_length=64)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('base_price_cents', models.PositiveIntegerField(default=2000)),
                ('autonomous_pr_add_on_enabled', models.BooleanField(default=False)),
                ('autonomous_pr_add_on_price_cents', models.PositiveIntegerField(default=200)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.customerorganization')),
            ],
            options={
                'ordering': ['organization__github_login'],
            },
        ),
    ]
