# Generated by Django 5.2.15 on 2026-06-05 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_installation_id', models.PositiveBigIntegerField(unique=True)),
                ('github_account_id', models.PositiveBigIntegerField()),
                ('github_account_login', models.CharField(max_length=255)),
                ('github_account_type', models.CharField(choices=[('organization', 'Organization'), ('user', 'User')], max_length=32)),
                ('repository_selection', models.CharField(choices=[('all', 'All repositories'), ('selected', 'Selected repositories')], default='selected', max_length=32)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('events', models.JSONField(blank=True, default=list)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_installations', to='accounts.customerorganization')),
            ],
            options={
                'ordering': ['github_account_login', 'github_installation_id'],
                'indexes': [models.Index(fields=['github_account_id'], name='github_app__github__471cee_idx'), models.Index(fields=['github_account_login'], name='github_app__github__906183_idx'), models.Index(fields=['suspended_at', 'deleted_at'], name='github_app__suspend_8a476e_idx')],
            },
        ),
    ]
