# Generated by Django 5.2.15 on 2026-06-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubinstallation',
            name='html_url',
            field=models.URLField(blank=True),
        ),
    ]
