# Generated by Django 5.2.15 on 2026-06-06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_app", "0002_githubinstallation_html_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivery_id", models.CharField(max_length=255, unique=True)),
                ("event", models.CharField(max_length=64)),
                ("action", models.CharField(blank=True, max_length=64)),
                (
                    "github_installation_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "github_repository_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("repository_full_name", models.CharField(blank=True, max_length=512)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("ignored", "Ignored"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=32,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "action"],
                        name="github_app__event_f60ea6_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="github_app__status_8db573_idx",
                    ),
                    models.Index(
                        fields=["github_installation_id"],
                        name="github_app__github__9b93cf_idx",
                    ),
                    models.Index(
                        fields=["github_repository_id"],
                        name="github_app__github__8c4009_idx",
                    ),
                ],
            },
        ),
    ]
