# Generated by Django 5.2.15 on 2026-06-05 21:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('github_user_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('github_login', models.CharField(blank=True, max_length=255)),
                ('github_avatar_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('github_account_id', models.PositiveBigIntegerField(unique=True)),
                ('github_login', models.CharField(max_length=255)),
                ('github_account_type', models.CharField(choices=[('organization', 'Organization'), ('user', 'User')], max_length=32)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['github_login'],
                'indexes': [models.Index(fields=['github_login'], name='accounts_cu_github__ad60cd_idx'), models.Index(fields=['deactivated_at'], name='accounts_cu_deactiv_744e4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('maintainer', 'Maintainer'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], max_length=32)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.customerorganization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization__github_login', 'user__email'],
                'indexes': [models.Index(fields=['role'], name='accounts_me_role_23d727_idx'), models.Index(fields=['deactivated_at'], name='accounts_me_deactiv_436c6c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deactivated_at__isnull', True)), fields=('user', 'organization'), name='unique_active_membership_per_user_org')],
            },
        ),
    ]
