# Generated by Django 5.2.15 on 2026-06-06 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("commit_sha", models.CharField(max_length=64)),
                ("constitution", models.JSONField(blank=True, default=dict)),
                ("entropy", models.JSONField(blank=True, default=dict)),
                ("opportunities", models.JSONField(blank=True, default=list)),
                ("snapshot_key", models.CharField(blank=True, max_length=512)),
                ("snapshot_checksum", models.CharField(blank=True, max_length=64)),
                ("knowledge_graph_key", models.CharField(blank=True, max_length=512)),
                (
                    "knowledge_graph_checksum",
                    models.CharField(blank=True, max_length=64),
                ),
                ("health_key", models.CharField(blank=True, max_length=512)),
                ("health_checksum", models.CharField(blank=True, max_length=64)),
                ("dead_code_key", models.CharField(blank=True, max_length=512)),
                ("dead_code_checksum", models.CharField(blank=True, max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_analyses",
                        to="accounts.customerorganization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="repositories.managedrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "repository", "-created_at"],
                        name="analysis_re_organiz_f2f2e8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("repository", "commit_sha"),
                        name="unique_repository_commit_analysis",
                    )
                ],
            },
        ),
    ]
