# Generated by Django 5.2.15 on 2026-06-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryanalysis',
            name='baseline_promoted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='repositoryanalysis',
            name='source',
            field=models.CharField(choices=[('first_scan', 'First scan'), ('session', 'Gardening session'), ('post_pr_refresh', 'Post-PR refresh'), ('manual_ingest', 'Manual ingest')], db_index=True, default='session', max_length=32),
        ),
    ]
